### ISSUE TITLE
assertion failed: !QUAD_CONTEXT.is_null()

### ISSUE THREAD

**Issue by SkyfallWasTaken** [optozorax/egui-macroquad#43]
When running the readme example, a window is opened, then immediately closes with this backtrace:
<details>
<summary><b>View backtrace...</b></summary>
<br>
<pre>
thread 'main' panicked at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.3.26/src/lib.rs:429:9:
assertion failed: !QUAD_CONTEXT.is_null()
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/std/src/panicking.rs:647:5
   1: core::panicking::panic_fmt
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:72:14
   2: core::panicking::panic
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/panicking.rs:144:5
   3: macroquad::get_quad_context
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.3.26/src/lib.rs:429:9
   4: macroquad::window::get_internal_gl
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.3.26/src/window.rs:51:23
   5: egui_macroquad::Egui::new
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-macroquad-0.15.0/src/lib.rs:72:34
   6: egui_macroquad::get_egui
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-macroquad-0.15.0/src/lib.rs:63:25
   7: egui_macroquad::ui
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/egui-macroquad-0.15.0/src/lib.rs:94:5
   8: viewer::amain::{{closure}}
             at ./crates/viewer/src/main.rs:10:9
   9: macroquad::exec::resume
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/exec.rs:72:11
  10: <macroquad::Stage as miniquad::event::EventHandler>::draw::{{closure}}
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/lib.rs:688:24
  11: <macroquad::Stage as miniquad::event::EventHandler>::draw::maybe_unwind
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/lib.rs:679:21
  12: <macroquad::Stage as miniquad::event::EventHandler>::draw
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/lib.rs:684:26
  13: miniquad::native::linux_x11::glx_main_loop
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniquad-0.4.0/src/native/linux_x11.rs:404:9
  14: miniquad::native::linux_x11::run
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniquad-0.4.0/src/native/linux_x11.rs:572:39
  15: miniquad::start
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/miniquad-0.4.0/src/lib.rs:253:17
  16: macroquad::Window::from_config
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/lib.rs:764:9
  17: macroquad::Window::new
             at /home/skyfall/.cargo/registry/src/index.crates.io-6f17d22bba15001f/macroquad-0.4.5/src/lib.rs:753:9
  18: viewer::main
             at ./crates/viewer/src/main.rs:3:1
  19: core::ops::function::FnOnce::call_once
             at /rustc/7cf61ebde7b22796c69757901dd346d0fe70bd97/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
</pre>
</details>

Using the following dependencies:
```toml
egui = "0.21"
egui-macroquad = "0.15.0"
macroquad = "0.4.5"
```

**Comment by conner-replogle** [comment]
were you able to figure it out?

**Comment by SkyfallWasTaken** [comment]
Unfortunately not, I ended up just ditching the gui part entirely :/
